### ISSUE TITLE
Manticore Nix package incompatible with SML/NJ >= 110.81

### ISSUE THREAD

**Issue by nalbyuites** [ManticoreProject/manticore#8]
@kavon Hello! I am facing an issue with building manticore [using Nix](https://nixos.org/nix/) using `SML/NJ v110.84` on x86_64. ([Failing build log](https://gist.github.com/nalbyuites/c85c82f6827a0e722e1a21613a70f010/c13231cf04bb407d02581e75697f29e88525700e#file-manticore_build-fail_smlnj-110_84-txt))

The error is being encountered with code in [amd64-gen-fn.sml](https://github.com/ManticoreProject/manticore/blob/trunk/src/tools/mc/codegen/amd64/amd64-gen-fn.sml
)
```
[compiling driver/(x86_64-linux.cm):../codegen/(sources.cm):(wrapper.cm):(group.cm):amd64/amd64-gen-fn.sml]
codegen/amd64/amd64-gen-fn.sml:110.33-118.7 Error: value type in structure doesn't match signature spec
    name: signBit
  spec:   int -> AMD64MLTree.rexp
  actual: int -> Label.label
codegen/amd64/amd64-gen-fn.sml:110.33-118.7 Error: value type in structure doesn't match signature spec
    name: negateSignBit
  spec:   int -> AMD64MLTree.rexp
  actual: int -> Label.label
Error: Compiler bug: ModuleUtil: getStr: bad entity
Compilation failed.
make[2]: *** [Makefile:83: pmlc.x86-linux] Error 1
make[2]: Leaving directory '/nix/store/5zy5w8jjm8vzaqjhhqpn9z7mpncmk01m-manticore-2017.08.22/repo_checkout/src/tools/mc'
make[1]: *** [Makefile:39: build] Error 2
make[1]: Leaving directory '/nix/store/5zy5w8jjm8vzaqjhhqpn9z7mpncmk01m-manticore-2017.08.22/repo_checkout/src'
make: *** [Makefile:58: build] Error 2
builder for '/nix/store/g21hjshf6pha15fdqmg6k34id718gijn-manticore-2017.08.22.drv' failed with exit code 2
error: build of '/nix/store/g21hjshf6pha15fdqmg6k34id718gijn-manticore-2017.08.22.drv' failed
```

The same build succeeds with `SML/NJ v110.79`. ([Working build log](https://hydra.nixos.org/build/84975838/nixlog/1)) -

```
[compiling driver/(x86_64-linux.cm):../codegen/(sources.cm):(wrapper.cm):(group.cm):amd64/amd64-gen-fn.sml]
codegen/amd64/amd64-gen-fn.sml:102.23-104.30 Warning: match nonexhaustive
          32 => ...
          64 => ...
  
codegen/amd64/amd64-gen-fn.sml:87.17-89.24 Warning: match nonexhaustive
          32 => ...
          64 => ...
```

Any help on why this is failing would be greatly appreciated!

**Comment by kavon** [comment]
It seems the version of Manticore in the Nix repository is incompatible with newer versions of SML/NJ, since Manticore is dated as a snapshot from 8/22/2017 in the logs. 

Newer SML/NJ does not work is because of [a change in MLRISC](https://www.smlnj.org/dist/working/110.81/110.81-README.html), which is part of SML/NJ, that was made in SML/NJ 110.81.

I'm not familiar with the process for updating a Nix package and changing its dependencies. Any pointers here would be greatly appreciated.

**Comment by nalbyuites** [comment]
@kavon Thanks a lot for replying. Indeed, this turned out to be so. I was able to build manticore from the latest snapshot 9/28/2018 locally against SML/NJ v110.84 .
```
$ /nix/store/00dapb3xdph68cs40gyxlmkfqrr8d595-manticore-2018.09.29/bin/pmlc -version
pmlc [x86_64-linux; 0.0.0 (); built 2018-12-01]
```
If you are okay with that revision, `47273c463fc3c5d0a0ae655cf75a4700bdb020b4` being used (stability-wise), and give the go-ahead, I will be happy to update the manticore Nix package as well as part of [my current PR](https://github.com/NixOS/nixpkgs/pull/50489).

The Nix derivation for manticore is [present here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/manticore/default.nix) and the dependencies are listed at the top of that file. I just changed the `rev`, `version` and `sha256` (sha256sum obtained from `nix-prefetch-url --unpack https://github.com/ManticoreProject/manticore/archive/47273c463fc3c5d0a0ae655cf75a4700bdb020b4.zip`) fields.

Here is a complete [tutorial on updating a Nix package](https://nixos.wiki/wiki/Nixpkgs/Update_a_package). If you would like to [check my changes locally](https://nixos.wiki/wiki/Nixpkgs/Update_a_package#Testing_the_changes), you can clone [this branch of my fork](https://github.com/nalbyuites/nixpkgs/tree/smlnj-110_84) of `nixpkgs` repo and run -
* nix-build -A smlnj
* nix-build -A manticore

**Comment by kavon** [comment]
@nalbyuites Yes, revision `47273c463` is the best version to update the package to. Thank you! :)
